language: node_js
node_js:
- '10'
cache:
  directories:
  - "~/.cache"
install: yarn install --frozen-lockfile
script:
- yarn build
deploy:
  provider: script
  script: node scripts/deploy.js
  on:
    branch: master
notifications:
  slack:
    secure: UeUBoKGcU9QGXbO6HZrEnn9c1DmjAow2Clqj5MNqg9MtIySy/5XkoOyiZCAUK5buWtt+yFqKf2JVPWoWCJsgE3t/cIJKHRDK6Ymf4TM8oz499pd7ogMVOToWRjKne61buB9Wp7RksFYLdSos01G3JfPUz7zcf7XqpLhDmAz28qgANnG6V/M5YBP1QDIMF88SwFXevdlbYicl7OXqpHy/ElqvFMcLZf6KvhR5QxfwB0Jo5femiuWx6QyvxnGQbYRC5B2bxCmBg9NLn8ZDdHNYUDgyCnRNIgem0yO5sBEEf42RlzKTNTpSfrzswAcdDNHV3rXGlKeSkNP3MzdHSaVWxgsRqnE2fu3ljJdhuu7XlGgWi40HMBZKOO6C6JD/EUHckQ+ZmQJZmpdR2Cc2FgfAp0STfNinclqwbJB+D0woskL2tvvJZ+Pn72/A7BzCiM3zy6WGo4s0B5p8G0HeMC8zeJ39QJdhTxD1pp0P3hQI/jPpnIBLTNhGXj3rwpHT5UtPrFI4FgLjPeWMuNXh3DPBY1gtSTNERiqPnICzR4+SEOtocDcreK4OUUE/Y7mWm1OlcIm1trEcaznfayWsx1tcKOTyK0zS+gVGyHBYpqobbDPgUnIB3MDj7ykqhEE31u2sW50XBIVzX2Qf8BkqC8+07VjTLnLt7KvswlMROmoVlUI=
