name: tests
on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
 
    - name: Setup node version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Test building
      run: yarn build

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      continue-on-error: true
      with:
        type: ${{ job.status }}
        job_name: '*${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}* - Connect-demo tests'
        username: 'GitHub Actions'
        icon_emoji: ':github:'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
